CREATE TABLE CLIENTE (
    NOME VARCHAR(100),
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(100) PRIMARY KEY,
    CADASTRO TIMESTAMP
);

CREATE TABLE ENSAIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TEMPO VARCHAR(100),
    PRECO NUMERIC(20,2)
);

CREATE TABLE USUARIO(
	LOGIN CHAR(100) PRIMARY KEY,
	SENHA CHAR(100),
	ROLES VARCHAR(10)
);

